force-app/package/core/objects/Mapped_sObject__c/Mapped_sObject__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Mapped sObjects</relationshipLabel>
    <relationshipName>Mapped_sObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <inlineHelpText>The metadata API name of the Mapped sObject</inlineHelpText>
    <label>sObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject_Field__c/Mapped_sObject_Field__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject_Field__c/fields/Mapped_sObject__c.field-meta.xml
<CustomField>
    <fullName>Mapped_sObject__c</fullName>
    <label>Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Mapped Fields</relationshipLabel>
    <relationshipName>Mapped_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/Schema_Mapping__c.object-meta.xml
<CustomObject>
    <label>Schema Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The related schema instructions</inlineHelpText>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Mappings</relationshipLabel>
    <relationshipName>Schema_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/Schema_Mapping_Version__c.object-meta.xml
<CustomObject>
    <description>The created output for the records that are being created</description>
    <label>Schema Mapping Version</label>
    <nameField>
        <displayFormat>SMV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Mapping Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <description>The generated prompt output generated based on the mappings</description>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output_Hash__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Hash__c</fullName>
    <inlineHelpText>A SHA1 hash of the prompt output to validate if any changes have been made since the last version</inlineHelpText>
    <label>Prompt Output Hash</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output_Length__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Length__c</fullName>
    <label>Prompt Output Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Schema Versions</relationshipLabel>
    <relationshipName>Schema_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/apex-unit-tests/classes/SchemaActionsCtrlTest.cls
@IsTest
private with sharing class SchemaActionsCtrlTest {
    
    @IsTest
    static void getActiveSchemaPromptOutputTest(){

        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;        
        insert sm;
        
        // Create the new mapping
        Schema_Mapping_Version__c smv = new Schema_Mapping_Version__c(
            Is_Latest__c            = true,
            Schema_Mapping__c       = sm.Id,
            Version_Number__c       = 1,
            Prompt_Output__c        = 'ABC',
            Prompt_Output_Length__c = 3,
            Prompt_Output_Hash__c   = Util.sha1('ABC')
        );
        insert smv;

        // Execute test
        Map<String,String> result = SchemaActionsCtrl.getActiveSchemaPromptOutput(sm.Id);

    }


    @IsTest
    static void createNewSchemaMappingVersionTest(){
        
        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;        
        insert sm;
        
        // Create the new mapping
        Schema_Mapping_Version__c smv = new Schema_Mapping_Version__c(
            Is_Latest__c            = true,
            Schema_Mapping__c       = sm.Id,
            Version_Number__c       = 1,
            Prompt_Output__c        = 'ABC',
            Prompt_Output_Length__c = 3,
            Prompt_Output_Hash__c   = Util.sha1('ABC')
        );
        insert smv;

        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;

        // Execute test
        SchemaActionsCtrl.createNewSchemaMappingVersion(sm.Id);

    }


    @IsTest
    static void addSObjectAndFieldsTest(){
        
        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;        
        insert sm;

        // Create the new mapping
        Schema_Mapping_Version__c smv = new Schema_Mapping_Version__c(
            Is_Latest__c            = true,
            Schema_Mapping__c       = sm.Id,
            Version_Number__c       = 1,
            Prompt_Output__c        = 'ABC',
            Prompt_Output_Length__c = 3,
            Prompt_Output_Hash__c   = Util.sha1('ABC')
        );
        insert smv;

        SchemaActionsCtrl.addSObjectAndFields(sm.Id, 'utl__Parent_Test_sObject__c', 'SObject Purpose', new String[]{'Name'});
    }


    @IsTest
    static void addChildSObjectAndFieldsTest(){
        
    // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;        
        insert sm;

        // Create the new mapping
        Schema_Mapping_Version__c smv = new Schema_Mapping_Version__c(
            Is_Latest__c            = true,
            Schema_Mapping__c       = sm.Id,
            Version_Number__c       = 1,
            Prompt_Output__c        = 'ABC',
            Prompt_Output_Length__c = 3,
            Prompt_Output_Hash__c   = Util.sha1('ABC')
        );
        insert smv;

        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;

        Mapped_sObject_Field__c parentMsof = new Mapped_sObject_Field__c();
        parentMsof.Name              = 'Name';
        parentMsof.Mapped_sObject__c = parentMso.Id;
        insert parentMsof;

        // Add child fields
        SchemaActionsCtrl.addChildSObjectAndFields(
            parentMso.Id, 
            'utl__Child_Test_sObject__c', 
            'utl__Parent_Test_sObject__c', 
            'SObject Purpose',
            new String[]{'Name'}
        );
    }
}