force-app/package/core/objects/Mapped_sObject__c/Mapped_sObject__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Mapped sObjects</relationshipLabel>
    <relationshipName>Mapped_sObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <inlineHelpText>The metadata API name of the Mapped sObject</inlineHelpText>
    <label>sObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject_Field__c/Mapped_sObject_Field__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject_Field__c/fields/Mapped_sObject__c.field-meta.xml
<CustomField>
    <fullName>Mapped_sObject__c</fullName>
    <label>Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Mapped Fields</relationshipLabel>
    <relationshipName>Mapped_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/Schema_Mapping__c.object-meta.xml
<CustomObject>
    <label>Schema Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The related schema instructions</inlineHelpText>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Mappings</relationshipLabel>
    <relationshipName>Schema_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/package/apex-unit-tests/classes/AddFieldsCtrlTest.cls
@IsTest
public with sharing class AddFieldsCtrlTest {
    
    @IsTest
    static void loadFieldsTest(){

        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;        
        insert sm;

        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;

        Mapped_sObject_Field__c parentMsof = new Mapped_sObject_Field__c();
        parentMsof.Name              = 'Name';
        parentMsof.Mapped_sObject__c = parentMso.Id;
        insert parentMsof;

        // Mapped_sObject__c
        AddFieldsCtrl.FieldData[] fields = AddFieldsCtrl.loadFields(parentMso.Id);

        // Assert there are fields
        Assert.areEqual(true, fields.size() > 0, 'Unexpected number of fields');
    }
    

    @IsTest
    static void addFields(){
        
        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;        
        insert sm;

        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;

        // Fields
        AddFieldsCtrl.FieldData[] fields = new AddFieldsCtrl.FieldData[]{};
        AddFieldsCtrl.FieldData   field  = new AddFieldsCtrl.FieldData();
        field.name = 'Name';
        fields.add(field);

        // Execute logic
        AddFieldsCtrl.addFields(parentMso.Id, JSON.serialize(fields));

        // Assert field has been added
        Assert.areEqual(1, [SELECT COUNT() FROM Mapped_sObject_Field__c],'Unexpected number of fields');
    }

    
}