force-app/package/core/objects/Mapped_sObject__c/Mapped_sObject__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject__c/fields/Parent_sObject__c.field-meta.xml
<CustomField>
    <fullName>Parent_sObject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Child_sObjects</relationshipLabel>
    <relationshipName>Child_sObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Parent_sObjectType__c.field-meta.xml
<CustomField>
    <fullName>Parent_sObjectType__c</fullName>
    <inlineHelpText>The sObjectType of the parent object</inlineHelpText>
    <label>Parent sObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <description>The API nName of the lookup field to the parent object</description>
    <inlineHelpText>The API nName of the lookup field to the parent object</inlineHelpText>
    <label>(Parent) Relationship Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Mapped sObjects</relationshipLabel>
    <relationshipName>Mapped_sObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <inlineHelpText>The metadata API name of the Mapped sObject</inlineHelpText>
    <label>sObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/Schema_Mapping__c.object-meta.xml
<CustomObject>
    <label>Schema Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The related schema instructions</inlineHelpText>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Mappings</relationshipLabel>
    <relationshipName>Schema_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/package/apex-unit-tests/classes/HierarchyUtilTest.cls
@IsTest
private with sharing class HierarchyUtilTest {

    @IsTest
    static void buildHierarchyTest() {

        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id;
        insert sm;

        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;

        Mapped_sObject__c childMso = new Mapped_sObject__c();
        childMso.Name                   = 'utl__Child_Test_sObject__c';
        childMso.sObjectType__c         = 'utl__Child_Test_sObject__c';
        childMso.Parent_sObjectType__c  = 'utl__Parent_Test_sObject__c';
        childMso.Relationship_Field__c  = 'utl__Parent_Test_sObject__c';
        childMso.Schema_Mapping__c      = sm.Id;
        childMso.Parent_sObject__c      = parentMso.Id;
        insert childMso;

        Mapped_sObject__c secondParentMso = new Mapped_sObject__c();
        secondParentMso.Name              = 'utl__Parent_Test_sObject__c 02';
        secondParentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        secondParentMso.Schema_Mapping__c = sm.Id;
        insert secondParentMso;


        Mapped_sObject__c secondChildMso = new Mapped_sObject__c();
        secondChildMso.Name                   = 'utl__Child_Test_sObject__c 02';
        secondChildMso.sObjectType__c         = 'utl__Child_Test_sObject__c';
        secondChildMso.Parent_sObjectType__c  = 'utl__Parent_Test_sObject__c';
        secondChildMso.Relationship_Field__c  = 'utl__Parent_Test_sObject__c';
        secondChildMso.Schema_Mapping__c      = sm.Id;
        secondChildMso.Parent_sObject__c      = secondParentMso.Id;
        insert secondChildMso;

        Mapped_sObject__c thirdParentMso = new Mapped_sObject__c();
        thirdParentMso.Name              = 'utl__Parent_Test_sObject__c 03';
        thirdParentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        thirdParentMso.Schema_Mapping__c = sm.Id;
        insert thirdParentMso;

        // Execute logic
        HierarchyUtil.TreeResult result = HierarchyUtil.buildHierarchy(sm.Id);

        // Assert
        Assert.areEqual(5, result.totalNodes, 'Unexpected number of sOBject in the hierarchy');

    }
}