force-app/package/core/objects/Mapped_sObject__c/Mapped_sObject__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject__c/fields/Ignore_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this field if you don&apos;t want any triggers to run</inlineHelpText>
    <label>Ignore Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Parent_sObject__c.field-meta.xml
<CustomField>
    <fullName>Parent_sObject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Child_sObjects</relationshipLabel>
    <relationshipName>Child_sObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Parent_sObjectType__c.field-meta.xml
<CustomField>
    <fullName>Parent_sObjectType__c</fullName>
    <inlineHelpText>The sObjectType of the parent object</inlineHelpText>
    <label>Parent sObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <description>The API nName of the lookup field to the parent object</description>
    <inlineHelpText>The API nName of the lookup field to the parent object</inlineHelpText>
    <label>(Parent) Relationship Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Mapped sObjects</relationshipLabel>
    <relationshipName>Mapped_sObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <inlineHelpText>The metadata API name of the Mapped sObject</inlineHelpText>
    <label>sObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject_Field__c/Mapped_sObject_Field__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject_Field__c/fields/Mapped_sObject__c.field-meta.xml
<CustomField>
    <fullName>Mapped_sObject__c</fullName>
    <label>Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Mapped Fields</relationshipLabel>
    <relationshipName>Mapped_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>There can be only one default schema instruction set. This default one should not be updated</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/Schema_Instruction_Version__c.object-meta.xml
<CustomObject>
    <description>Version data of the Schema Instructions</description>
    <label>Schema Instruction Version</label>
    <nameField>
        <displayFormat>SIV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Instruction Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The latest versions is the active version that will outputted in the prompt template</inlineHelpText>
    <label>Is Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <inlineHelpText>The output as it will be displayed in the prompt template.</inlineHelpText>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output_Hash__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Hash__c</fullName>
    <inlineHelpText>A SHA1 hash to validate changes between the latest versions</inlineHelpText>
    <label>Prompt Output Hash</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Instruction Versions</relationshipLabel>
    <relationshipName>Schema_Instruction_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <inlineHelpText>The version of the instructions, will auto increase by 1</inlineHelpText>
    <label>Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping__c/Schema_Mapping__c.object-meta.xml
<CustomObject>
    <label>Schema Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The related schema instructions</inlineHelpText>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Mappings</relationshipLabel>
    <relationshipName>Schema_Mappings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/Schema_Mapping_Version__c.object-meta.xml
<CustomObject>
    <description>The created output for the records that are being created</description>
    <label>Schema Mapping Version</label>
    <nameField>
        <displayFormat>SMV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Mapping Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <description>The generated prompt output generated based on the mappings</description>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output_Hash__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Hash__c</fullName>
    <inlineHelpText>A SHA1 hash of the prompt output to validate if any changes have been made since the last version</inlineHelpText>
    <label>Prompt Output Hash</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output_Length__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Length__c</fullName>
    <label>Prompt Output Length</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Schema Versions</relationshipLabel>
    <relationshipName>Schema_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/apex-unit-tests/classes/TriggerTest.cls
@IsTest
private with sharing class TriggerTest {


    @IsTest
    static void triggerTest(){

        Schema_Instruction__c si = new Schema_Instruction__c();
        si.Is_Default__c        = true;
        si.Name                 = Constant.DEFAULT_INSTRUCTION_NAME;
        si.Ignore_Triggers__c   = true;
        insert si;

        si.Ignore_Triggers__c   = true;
        update si;

        try{
            // Should not be possble
            delete si;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('The default record cannot be deleted.'),
                'Unexpected Exception Message'
            );
        }


        Schema_Instruction_Version__c siv = new Schema_Instruction_Version__c();
        siv.Schema_Instruction__c = si.Id;
        siv.Prompt_Output__c = 'ABC';
        siv.Prompt_Output_Hash__c = Util.sha1('ABC');
        siv.Prompt_Output_Length__c = 3;
        insert siv;

        si.Ignore_Triggers__c   = true;
        update siv;

        // Create a schema
        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = si.Id;
        insert sm;
        update sm;


        
        // Create the new mapping
        Schema_Mapping_Version__c smv = new Schema_Mapping_Version__c(
            Is_Latest__c            = true,
            Schema_Mapping__c       = sm.Id,
            Version_Number__c       = 1,
            Prompt_Output__c        = 'ABC',
            Prompt_Output_Length__c = 3,
            Prompt_Output_Hash__c   = Util.sha1('ABC')
        );
        insert smv;
        update smv;



        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;
        update parentMso;

        Mapped_sObject_Field__c parentMsof = new Mapped_sObject_Field__c();
        parentMsof.Name              = 'Name';
        parentMsof.Mapped_sObject__c = parentMso.Id;
        insert parentMsof;
        update parentMsof;

        Mapped_sObject__c childMso = new Mapped_sObject__c();
        childMso.Name                   = 'utl__Child_Test_sObject__c';
        childMso.sObjectType__c         = 'utl__Child_Test_sObject__c';
        childMso.Parent_sObjectType__c  = 'utl__Parent_Test_sObject__c';
        childMso.Relationship_Field__c  = 'utl__Parent_Test_sObject__c';
        childMso.Schema_Mapping__c      = sm.Id;
        childMso.Parent_sObject__c      = parentMso.Id;
        insert childMso;
        update childMso;

        // Add field
        Mapped_sObject_Field__c childMsof = new Mapped_sObject_Field__c();
        childMsof.Name              = 'Name';
        childMsof.Mapped_sObject__c = childMso.Id;
        insert childMsof;
        update childMsof;

        // Test deletes
        delete childMsof;
        delete childMso;
    }


    @IsTest
    static void testProblemChild(){

        Schema_Instruction__c si = new Schema_Instruction__c();
        si.Is_Default__c        = true;
        si.Name                 = Constant.DEFAULT_INSTRUCTION_NAME;
        insert si;

        Schema_Mapping__c sm = new Schema_Mapping__c();
        sm.Name = 'Test Schema';
        sm.Schema_Instruction__c = si.Id;
        insert sm;
        
        Mapped_sObject__c parentMso = new Mapped_sObject__c();
        parentMso.Name              = 'utl__Parent_Test_sObject__c';
        parentMso.sObjectType__c    = 'utl__Parent_Test_sObject__c';
        parentMso.Schema_Mapping__c = sm.Id;
        insert parentMso;

        try{
            Mapped_sObject__c problemChildMso = new Mapped_sObject__c();
            problemChildMso.Parent_sObject__c      = parentMso.Id;
            problemChildMso.Name                   = 'Invalid';
            problemChildMso.sObjectType__c         = 'Invalid';

            // Execute test
            insert problemChildMso;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('No sObject with the name: "Invalid" found in the metadata.'),
                'Unexpected Exception Message: ' + e.getMessage() + e.getStackTraceString()
            );
        }

        
        try{
            Mapped_sObject__c problemChildMso = new Mapped_sObject__c();
            problemChildMso.Parent_sObject__c      = parentMso.Id;
            problemChildMso.Name                   = 'utl__Child_Test_sObject__c';
            problemChildMso.sObjectType__c         = 'utl__Child_Test_sObject__c';

            // Execute test
            insert problemChildMso;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('The Parent sObjectType field cannot be blank if a Parent Mapped sObject is specified.'),
                'Unexpected Exception Message: ' + e.getMessage() + e.getStackTraceString()
            );
        }


        try{

            Mapped_sObject__c problemChildMso = new Mapped_sObject__c();
            problemChildMso.Parent_sObject__c      = parentMso.Id;
            problemChildMso.Name                   = 'utl__Child_Test_sObject__c';
            problemChildMso.sObjectType__c         = 'utl__Child_Test_sObject__c';
            problemChildMso.Parent_sObjectType__c  = 'utl__Parent_Test_sObject__c';

            // Execute test
            insert problemChildMso;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('The (Parent) Relationship Field cannot be blank if a Parent Mapped sObject is specified.'),
                'Unexpected Exception Message: ' + e.getMessage() + e.getStackTraceString()
            );
        }


        try{
            Mapped_sObject__c problemChildMso = new Mapped_sObject__c();
            problemChildMso.Parent_sObject__c      = parentMso.Id;
            problemChildMso.Name                   = 'utl__Child_Test_sObject__c';
            problemChildMso.sObjectType__c         = 'utl__Child_Test_sObject__c';
            problemChildMso.Parent_sObjectType__c  = 'Invalid';
            problemChildMso.Relationship_Field__c  = 'utl__Parent_Test_sObject__c';

            // Execute test
            insert problemChildMso;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('No sObject with the name: "Invalid" found in the metadata.'),
                'Unexpected Exception Message: ' + e.getMessage() + e.getStackTraceString()
            );
        }


        try{
            Mapped_sObject__c problemChildMso = new Mapped_sObject__c();
            problemChildMso.Parent_sObject__c      = parentMso.Id;
            problemChildMso.Name                   = 'Organization';
            problemChildMso.sObjectType__c         = 'Organization';
            problemChildMso.Parent_sObjectType__c  = 'utl__Parent_Test_sObject__c';
            problemChildMso.Relationship_Field__c  = 'utl__Parent_Test_sObject__c';

            // Execute test
            insert problemChildMso;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('"utl__Parent_Test_sObject__c" does not have any child relationship(s) to "Organization"'),
                'Unexpected Exception Message: ' + e.getMessage() + e.getStackTraceString()
            );
        }


        try{
            Mapped_sObject__c problemChildMso = new Mapped_sObject__c();
            problemChildMso.Parent_sObject__c      = parentMso.Id;
            problemChildMso.Name                   = 'utl__Child_Test_sObject__c';
            problemChildMso.sObjectType__c         = 'utl__Child_Test_sObject__c';
            problemChildMso.Parent_sObjectType__c  = 'utl__Parent_Test_sObject__c';
            problemChildMso.Relationship_Field__c  = 'OwnerId';

            // Execute test
            insert problemChildMso;

            // This method will fail the test as it should not be reached
            utl.Tst.assertExceptionHasBeenThrow();

        }catch(System.DmlException e){
            Assert.areEqual(
                true,
                e.getMessage().contains('The field "OwnerId" on sObject "utl__Child_Test_sObject__c" does not lookup to sObject "utl__Parent_Test_sObject__c"'),
                'Unexpected Exception Message: ' + e.getMessage() + e.getStackTraceString()
            );
        }
    }
}