force-app/package/core/objects/Mapped_sObject__c/Mapped_sObject__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject__c/fields/Parent_sObject__c.field-meta.xml
<CustomField>
    <fullName>Parent_sObject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Child_sObjects</relationshipLabel>
    <relationshipName>Child_sObjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Parent_sObjectType__c.field-meta.xml
<CustomField>
    <fullName>Parent_sObjectType__c</fullName>
    <inlineHelpText>The sObjectType of the parent object</inlineHelpText>
    <label>Parent sObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <description>The API nName of the lookup field to the parent object</description>
    <inlineHelpText>The API nName of the lookup field to the parent object</inlineHelpText>
    <label>(Parent) Relationship Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Mapped sObjects</relationshipLabel>
    <relationshipName>Mapped_sObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <inlineHelpText>The metadata API name of the Mapped sObject</inlineHelpText>
    <label>sObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject_Field__c/Mapped_sObject_Field__c.object-meta.xml
<CustomObject>
    <label>Mapped sObject Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapped sObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Mapped_sObject_Field__c/fields/Mapped_sObject__c.field-meta.xml
<CustomField>
    <fullName>Mapped_sObject__c</fullName>
    <label>Mapped sObject</label>
    <referenceTo>Mapped_sObject__c</referenceTo>
    <relationshipLabel>Mapped Fields</relationshipLabel>
    <relationshipName>Mapped_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Mapped_sObject_Field__c/fields/Purpose_Description__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Description__c</fullName>
    <label>Purpose Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping__c/Schema_Mapping__c.object-meta.xml
<CustomObject>
    <label>Schema Mapping</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping__c/fields/Latest_Version__c.field-meta.xml
<CustomField>
    <fullName>Latest_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Version</label>
    <referenceTo>Schema_Mapping_Version__c</referenceTo>
    <relationshipLabel>Schema Mappings</relationshipLabel>
    <relationshipName>Schema_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping__c/fields/Purpose_Description__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Description__c</fullName>
    <label>Purpose Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/Schema_Mapping_Version__c.object-meta.xml
<CustomObject>
    <description>The created output for the records that are being created</description>
    <label>Schema Mapping Version</label>
    <nameField>
        <displayFormat>SMV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Mapping Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <description>The generated prompt output generated based on the mappings</description>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Schema_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Schema_Mapping__c</fullName>
    <label>Schema Mapping</label>
    <referenceTo>Schema_Mapping__c</referenceTo>
    <relationshipLabel>Schema Versions</relationshipLabel>
    <relationshipName>Schema_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Mapping_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/ui/classes/SchemaActionsCtrl.cls
/**
 * @author         Justus van den Berg (jfwberg@gmail.com)
 * @date           December 2025
 * @copyright      (c) 2025 Justus van den Berg
 * @license        MIT (See LICENSE file in the project root)
 * @description    LWC Controller Class for managing schema actions
 * 
 */
public with sharing class SchemaActionsCtrl {

    @AuraEnabled
    public static Map<String,String> getActiveSchemaPromptOutput(String recordId){
        try {
            // Validate record exists
            SchemaUtil.validateRecordId(recordId,Schema.Schema_Mapping__c.getSObjectType());

            // recordId is Schema_Mapping__c. Latest_Version__c is a lookup to Schema_Mapping_Version__c.
            // Return Latest_Version__r.Prompt_Output__c.
            Schema_Mapping__c sm = [
                SELECT
                    Latest_Version__r.Prompt_Output__c,
                    Latest_Version__r.Version_Number__c
                FROM Schema_Mapping__c
                WHERE Id = :recordId
                WITH SYSTEM_MODE
                LIMIT 1
            ];

            return new Map<String,String>{
                'label'         => 'Prompt Output Version: ' + (sm.Latest_Version__r != null ? sm.Latest_Version__r.Version_Number__c : null) ?.toString(),
                'promptOutput'  => (sm.Latest_Version__r != null ? sm.Latest_Version__r.Prompt_Output__c :  null )
            };
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static Map<String,Object> createNewSchemaMappingVersion(String recordId){
        try {
            // Create the records and return the created record details
            return SchemaMappingUtil.createNewSchemaMappingVersion(recordId);

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static void addSObjectAndFields(String recordId, String sobjectApiName, String purposeDescription, String[] selectedFieldApiNames){
        try {
            // Validate record exists
            SchemaUtil.validateRecordId(recordId, Schema.Schema_Mapping__c.getSObjectType());

            if(String.isBlank(sobjectApiName)){
                throw new StringException('Please select an sObject before you continue.');
            }

            if ((selectedFieldApiNames?.isEmpty() == true) || selectedFieldApiNames == null) {
                throw new StringException('Please select at least one sObject field to add to the Schema Mapping.');
            }

            Mapped_sObject__c mso = new Mapped_sObject__c(
                Schema_Mapping__c       = recordId,
                Name                    = sobjectApiName,
                sObjectType__c          = sobjectApiName,
                Purpose_Description__c  = purposeDescription
            );
            insert as system mso;


            Mapped_sObject_Field__c[] msofs = new Mapped_sObject_Field__c[]{};

            for(String fieldName : selectedFieldApiNames){
                msofs.add( new Mapped_sObject_Field__c(
                    Mapped_sObject__c = mso.Id,
                    Name              = fieldName
                ));
            }

            insert as system msofs;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static void addChildSObjectAndFields(String recordId, String sobjectApiName, String relationshipField, String purposeDescription, String[] selectedFieldApiNames){
        try {

            // Validate the record id is not blank
            SchemaUtil.validateRecordId(recordId, SChema.Mapped_sObject__c.getSObjectType());

            // Fetch the schema mapping from the parent record
            // This is a mandatory field
            Mapped_sObject__c[] parentMsos = [SELECT Id, Schema_Mapping__c, sObjectType__c FROM Mapped_sObject__c WHERE Id =:recordId LIMIT 1];

            // Validate a parent is found
            if (parentMsos?.isEmpty() != false) {
                throw new StringException('No parent Mapped sObject found for Id "'+recordId+'"');
            }

            // Create a new (child) mapped sObject
            Mapped_sObject__c mso = new Mapped_sObject__c(
                Schema_Mapping__c       = parentMsos[0].Schema_Mapping__c,
                Name                    = sobjectApiName,
                sObjectType__c          = sobjectApiName,
                Purpose_Description__c  = purposeDescription,
                Parent_SObject__c       = parentMsos[0].Id,
                Parent_SObjectType__c   = parentMsos[0].sObjectType__c,
                Relationship_Field__c   = relationshipField
            );
            insert as system mso;


            Mapped_sObject_Field__c[] msofs = new Mapped_sObject_Field__c[]{};

            for(String fieldName : selectedFieldApiNames){
                msofs.add( new Mapped_sObject_Field__c(
                    Mapped_sObject__c = mso.Id,
                    Name              = fieldName
                ));
            }

            insert as system msofs;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}