force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/Schema_Instruction_Version__c.object-meta.xml
<CustomObject>
    <description>Version data of the Schema Instructions</description>
    <label>Schema Instruction Version</label>
    <nameField>
        <displayFormat>SIV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Instruction Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <inlineHelpText>The output as it will be displayed in the prompt template.</inlineHelpText>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Instruction Versions</relationshipLabel>
    <relationshipName>Schema_Instruction_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/apex-unit-tests/classes/SchemaInstructionCtrlTest.cls
@IsTest
private with sharing class SchemaInstructionCtrlTest {
    
    @IsTest
    static void isDefaultInstructionTest(){
        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        Boolean result = SchemaInstructionCtrl.isDefaultInstruction(
            [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id
        );

        Assert.areEqual(true, result,'Expected Default instructions');
    }

    @IsTest
    static void loadSchemaInstructionVersionTest(){
        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        String result = SchemaInstructionCtrl.loadSchemaInstructionVersion(
            [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id
        );
    }


    @IsTest
    static void resetDefaultInstructionTest(){
        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        Map<String,Object> result = SchemaInstructionCtrl.resetDefaultInstruction();

        Assert.areEqual(true, !result.isEmpty(),'Expected results in the version map');
    }


    @IsTest
    static void createSchemaInstructionVersionTest(){

        // Create the default instructions
        SchemaInstructionUtil.insertDefaultInstructions();

        Map<String,Object> result = SchemaInstructionCtrl.createSchemaInstructionVersion(
            [SELECT Id FROM Schema_Instruction__c WHERE Name = :Constant.DEFAULT_INSTRUCTION_NAME WITH SYSTEM_MODE LIMIT 1]?.Id,
            'new instructions'
        );
        
        Assert.areEqual(
            'new instructions',
            [SELECT Prompt_Output__c FROM Schema_Instruction_Version__c WHERE Id = :((String)result.get('versionRecordId')) LIMIT 1 ]?.Prompt_Output__c,
            'Unexpected instructions...'
        );
    }
}