force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>There can be only one default schema instruction set. This default one should not be updated</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction__c/fields/Latest_Version__c.field-meta.xml
<CustomField>
    <fullName>Latest_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The latest version of the instructions</inlineHelpText>
    <label>Latest Version</label>
    <referenceTo>Schema_Instruction_Version__c</referenceTo>
    <relationshipLabel>Schema Instructions</relationshipLabel>
    <relationshipName>Schema_Instructions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/Schema_Instruction_Version__c.object-meta.xml
<CustomObject>
    <description>Version data of the Schema Instructions</description>
    <label>Schema Instruction Version</label>
    <nameField>
        <displayFormat>SIV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Instruction Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The latest versions is the active version that will outputted in the prompt template</inlineHelpText>
    <label>Is Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <inlineHelpText>The output as it will be displayed in the prompt template.</inlineHelpText>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output_Hash__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Hash__c</fullName>
    <inlineHelpText>A SHA1 hash to validate changes between the latest versions</inlineHelpText>
    <label>Prompt Output Hash</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Instruction Versions</relationshipLabel>
    <relationshipName>Schema_Instruction_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <inlineHelpText>The version of the instructions, will auto increase by 1</inlineHelpText>
    <label>Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/core/classes/SchemaInstructionUtil.cls
/**
 * @author         Justus van den Berg (jfwberg@gmail.com)
 * @date           December 2025
 * @copyright      (c) 2025 Justus van den Berg
 * @license        MIT (See LICENSE file in the project root)
 * @description    Class that contains a set of utilities for generating Instruction records
 */
public with sharing class SchemaInstructionUtil {
    
    public static Boolean getDefaultRecordExists(){
        
        // Return true if the default record exists
        return String.isNotBlank([
            SELECT Id FROM Schema_Instruction__c 
            WHERE Is_Default__c = true 
            AND Name = :Constant.DEFAULT_INSTRUCTION_NAME 
            WITH SYSTEM_MODE 
            LIMIT 1
        ]?.Id);
    }
    
    
    public static Schema_Instruction__c getDefaultRecord(){

        Schema_Instruction__c[] defaultRecords = [
                SELECT
                    Id,
                    Name,
                    Latest_Version__c,
                    Latest_Version__r.Prompt_Output__c
                FROM Schema_Instruction__c
                WHERE Is_Default__c = true
                AND Name = :Constant.DEFAULT_INSTRUCTION_NAME
                WITH SYSTEM_MODE
                LIMIT 1
        ];

        if(defaultRecords.isEmpty()){
            throw new SchemaInstructionException(Constant.MSG_NO_DEFAULT_INSTRUCTION);
        }

        // Return the default instruction record
        return defaultRecords[0];
    }


    public static String getDefaultInstruction(){
        // Return the default instruction value
        return Util.getStaticResourceBody(Constant.DEFAULT_INSTRUCTIONS_SR_NAME);
    }

    @future
    public static void insertDefaultInstructionsAsync(){
        insertDefaultInstructions();
    }

    /**
     * @description Method that inserts the default instructions based on the Static Resource
     */
    public static void insertDefaultInstructions() {

        if(getDefaultRecordExists()){
            return;
        }

        // Create instructions
        Schema_Instruction__c instructionRecord = new Schema_Instruction__c();
        instructionRecord.Name           = Constant.DEFAULT_INSTRUCTION_NAME;
        instructionRecord.Is_Default__c  = true;
        instructionRecord.External_Id__c = Constant.VAL_INSTRUCTION_UUID;
        insert as system instructionRecord;

        // Create default instructions based on the static resource body
        Schema_Instruction_Version__c instructionVersionRecord = new Schema_Instruction_Version__c();
        instructionVersionRecord.Schema_Instruction__c   = instructionRecord.Id;
        instructionVersionRecord.Prompt_Output__c        = getDefaultInstruction();
        instructionVersionRecord.Prompt_Output_Length__c = (instructionVersionRecord.Prompt_Output__c ?? '')?.length();
        instructionVersionRecord.Prompt_Output_Hash__c   = Util.sha1((instructionVersionRecord.Prompt_Output__c ?? ''));
        instructionVersionRecord.Is_Latest__c            = true;
        instructionVersionRecord.External_Id__c          = Constant.VAL_INSTRUCTION_VERSION_UUID;
        instructionVersionRecord.Version_Number__c       = 1;
        insert as system instructionVersionRecord;

        // Update the parent version with the latest
        instructionRecord.Latest_Version__c = instructionVersionRecord.Id;
        update as system instructionRecord;
    }


    /** **************************************************************************************************** **
     **                                     PRIVATE EXCEPTION CLASSES                                        **
     ** **************************************************************************************************** **/
    /**
     * @description An exception that is thrown when something goes wrong related to the schema instruction
     */
    public class SchemaInstructionException extends Exception{}
}