force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>There can be only one default schema instruction set. This default one should not be updated</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction__c/fields/Latest_Version__c.field-meta.xml
<CustomField>
    <fullName>Latest_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The latest version of the instructions</inlineHelpText>
    <label>Latest Version</label>
    <referenceTo>Schema_Instruction_Version__c</referenceTo>
    <relationshipLabel>Schema Instructions</relationshipLabel>
    <relationshipName>Schema_Instructions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/Schema_Instruction_Version__c.object-meta.xml
<CustomObject>
    <description>Version data of the Schema Instructions</description>
    <label>Schema Instruction Version</label>
    <nameField>
        <displayFormat>SIV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Instruction Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The latest versions is the active version that will outputted in the prompt template</inlineHelpText>
    <label>Is Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output__c</fullName>
    <inlineHelpText>The output as it will be displayed in the prompt template.</inlineHelpText>
    <label>Prompt Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Prompt_Output_Hash__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Output_Hash__c</fullName>
    <inlineHelpText>A SHA1 hash to validate changes between the latest versions</inlineHelpText>
    <label>Prompt Output Hash</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Instruction Versions</relationshipLabel>
    <relationshipName>Schema_Instruction_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <inlineHelpText>The version of the instructions, will auto increase by 1</inlineHelpText>
    <label>Version Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/package/ui/classes/SchemaInstructionCtrl.cls
/**
 * @author         Justus van den Berg (jfwberg@gmail.com)
 * @date           December 2025
 * @copyright      (c) 2025 Justus van den Berg
 * @license        MIT (See LICENSE file in the project root)
 * @description    LWC Controller Class for managing schema instructions
 * 
 */
public with sharing class SchemaInstructionCtrl {

    @AuraEnabled
    public static Boolean isDefaultInstruction(String recordId){
        try {
            // Validate record exists
            SchemaUtil.validateRecordId(recordId, Schema.Schema_Instruction__c.getSObjectType());

            // Fetch the latest version
            return [
                SELECT
                    Id
                FROM Schema_Instruction__c
                WHERE Is_Default__c = true
                AND Name = :Constant.DEFAULT_INSTRUCTION_NAME
                WITH SYSTEM_MODE
                LIMIT 1
            ]?.Id == recordId;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static String loadSchemaInstructionVersion(String recordId){
        try {
            // Validate record exists
            SchemaUtil.validateRecordId(recordId, Schema.Schema_Instruction__c.getSObjectType());

            // Fetch the latest version
            return SchemaInstructionUtil.getDefaultRecord()?.Latest_Version__r.Prompt_Output__c;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled 
    public static Map<String,Object> resetDefaultInstruction(){
        try{
            return createSchemaInstructionVersion(
                SchemaInstructionUtil.getDefaultRecord()?.Id,
                SchemaInstructionUtil.getDefaultInstruction()
            );
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }   
    }


    @AuraEnabled
    public static Map<String,Object> createSchemaInstructionVersion(String recordId, String instructions){
        try {
            
            // Validate record exists
            SchemaUtil.validateRecordId(recordId, Schema.Schema_Instruction__c.getSObjectType());

            Schema_Instruction_Version__c siv = new Schema_Instruction_Version__c(
                Is_Latest__c            = true,
                Schema_Instruction__c   = recordId,
                Version_Number__c       = ([SELECT Version_Number__c FROM Schema_Instruction_Version__c WHERE Schema_Instruction__c = :recordId AND Version_Number__c != NULL WITH SYSTEM_MODE ORDER BY Version_Number__c DESC LIMIT 1]?.Version_Number__c ?? 0) + 1,
                Prompt_Output__c        = instructions,
                External_Id__c          = UUID.randomUUID().toString(),
                Prompt_Output_Length__c = instructions?.length(),
                Prompt_Output_Hash__c   = EncodingUtil.convertToHex(Crypto.generateDigest('SHA1', Blob.valueOf(instructions)))
            );

            // Create the new version
            insert as system siv;

            // Return the version details
            return new Map<String,Object>{
                'versionRecordId'   => siv.Id,
                'versionRecordName' => [SELECT Name FROM Schema_Instruction_Version__c WHERE Id=:siv.Id WITH SYSTEM_MODE LIMIT 1 ]?.Name,
                'versionNumber'     => String.valueOf(siv.Version_Number__c)
            };

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}