force-app/package/core/objects/Schema_Instruction__c/Schema_Instruction__c.object-meta.xml
<CustomObject>
    <description>Contains reusable detailed LLM instructions that can be used in prompt templates as part of constructing the schema</description>
    <label>Schema Instruction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/Schema_Instruction_Version__c.object-meta.xml
<CustomObject>
    <description>Version data of the Schema Instructions</description>
    <label>Schema Instruction Version</label>
    <nameField>
        <displayFormat>SIV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schema Instruction Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/package/core/objects/Schema_Instruction_Version__c/fields/Schema_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Schema_Instruction__c</fullName>
    <label>Schema Instruction</label>
    <referenceTo>Schema_Instruction__c</referenceTo>
    <relationshipLabel>Schema Instruction Versions</relationshipLabel>
    <relationshipName>Schema_Instruction_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package/apex-unit-tests/classes/SchemaInstructionUtilTest.cls
@IsTest
private with sharing class SchemaInstructionUtilTest {
    
    // Create a test uses with the test util permission set
    private static User runAsUser = utl.Tst.createRunAsUser(
        utl.Tst.STANDARD_USER_PROFILE,
        Constant.VAL_PERMISSION_SET_NAME  
    ); 


    @IsTest
    static void insertDefaultInstructionsTest(){
        
        // Execute the flow logic and create test records
        System.runAs(runAsUser){
            SchemaInstructionUtil.insertDefaultInstructions();
        }

        Assert.areEqual(1, [SELECT COUNT() FROM Schema_Instruction__c],         'Expected 01 Instruction__c record to exist.'         );
        Assert.areEqual(1, [SELECT COUNT() FROM Schema_Instruction_Version__c], 'Expected 01 Instruction_Version__c records to exist.');
    }
}